<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="62154" started-at="2017-04-23T11:25:22Z" finished-at="2017-04-23T11:26:25Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="62154" started-at="2017-04-23T11:25:22Z" finished-at="2017-04-23T11:26:25Z">
      <class name="test_case.read_write_testng">
        <test-method status="PASS" signature="open()[pri:0, instance:test_case.read_write_testng@1e88b3c]" name="open" is-config="true" duration-ms="329" started-at="2017-04-23T16:55:22Z" finished-at="2017-04-23T16:55:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- open -->
        <test-method status="FAIL" signature="start()[pri:0, instance:test_case.read_write_testng@1e88b3c]" name="start" duration-ms="61786" started-at="2017-04-23T16:55:23Z" finished-at="2017-04-23T16:56:25Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:55)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.Assert.assertTrue(Assert.java:31)
	at appModule.SignIn_Action_testng.Execute(SignIn_Action_testng.java:100)
	at test_case.read_write_testng.start(read_write_testng.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="PASS" signature="end()[pri:0, instance:test_case.read_write_testng@1e88b3c]" name="end" is-config="true" duration-ms="1" started-at="2017-04-23T16:56:25Z" finished-at="2017-04-23T16:56:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
      </class> <!-- test_case.read_write_testng -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
